"""empty message

Revision ID: 08a6c1aa35fe
Revises: 8ce8a5ea43f6
Create Date: 2026-03-30 11:02:49.223325

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08a6c1aa35fe'
down_revision = '8ce8a5ea43f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('t_role_menu',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('menu_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['menu_id'], ['t_menu.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['t_role.id'], ),
    sa.PrimaryKeyConstraint('id', 'role_id', 'menu_id'),
    mysql_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('t_role_menu')
    # ### end Alembic commands ###
