"""empty message

Revision ID: 1718e371ea50
Revises: 31bb7ad5e813
Create Date: 2026-03-19 19:46:22.316838

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1718e371ea50'
down_revision = '31bb7ad5e813'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t_menu', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 't_menu', ['pid'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t_menu', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
