"""empty message

Revision ID: 3a75f5c37523
Revises: 039675258ee6
Create Date: 2026-03-30 10:55:32.990607

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a75f5c37523'
down_revision = '039675258ee6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t_role_menu', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 't_menu', ['menu_id'], ['id'])
        batch_op.create_foreign_key(None, 't_role', ['role_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t_role_menu', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
