"""empty message

Revision ID: 405b6400fe4b
Revises: 7551883d26f8
Create Date: 2026-03-19 21:32:24.399969

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '405b6400fe4b'
down_revision = '7551883d26f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t_menu', schema=None) as batch_op:
        batch_op.add_column(sa.Column('level', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t_menu', schema=None) as batch_op:
        batch_op.drop_column('level')

    # ### end Alembic commands ###
