"""empty message

Revision ID: 4a12fa8c6d42
Revises: f3609bf7da3d
Create Date: 2026-03-15 23:39:53.403362

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4a12fa8c6d42'
down_revision = 'f3609bf7da3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t_user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.String(length=64), nullable=False))
        batch_op.drop_column('pwd')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t_user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pwd', mysql.VARCHAR(length=64), nullable=False))
        batch_op.drop_column('password')

    # ### end Alembic commands ###
