"""empty message

Revision ID: 4d3cdb271846
Revises: 3a75f5c37523
Create Date: 2026-03-30 10:56:57.603166

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d3cdb271846'
down_revision = '3a75f5c37523'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('t_role_menu',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('menu_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['menu_id'], ['t_menu.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['t_role.id'], ),
    sa.PrimaryKeyConstraint('role_id', 'menu_id'),
    mysql_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('t_role_menu')
    # ### end Alembic commands ###
