"""empty message

Revision ID: 8ce8a5ea43f6
Revises: 4d3cdb271846
Create Date: 2026-03-30 11:02:31.444914

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ce8a5ea43f6'
down_revision = '4d3cdb271846'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t_role_menu', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), autoincrement=True, nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t_role_menu', schema=None) as batch_op:
        batch_op.drop_column('id')

    # ### end Alembic commands ###
