"""empty message

Revision ID: a5437fb0017d
Revises: 08a6c1aa35fe
Create Date: 2026-04-02 11:27:49.383525

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a5437fb0017d'
down_revision = '08a6c1aa35fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t_role_menu', schema=None) as batch_op:
        batch_op.drop_column('id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t_role_menu', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False))

    # ### end Alembic commands ###
