"""empty message

Revision ID: aeb376551483
Revises: e4e80c1ed7d1
Create Date: 2026-04-10 22:17:17.296410

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aeb376551483'
down_revision = 'e4e80c1ed7d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t_attribute', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('name'))
        batch_op.drop_index(batch_op.f('val'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t_attribute', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('val'), ['val'], unique=True)
        batch_op.create_index(batch_op.f('name'), ['name'], unique=True)

    # ### end Alembic commands ###
