"""empty message

Revision ID: cc59c1e51632
Revises: feb4745aeba9
Create Date: 2026-03-27 22:20:37.796915

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cc59c1e51632'
down_revision = 'feb4745aeba9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t_role', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(length=128), nullable=True))
        batch_op.drop_index(batch_op.f('desc'))
        batch_op.create_unique_constraint(None, ['description'])
        batch_op.drop_column('desc')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t_role', schema=None) as batch_op:
        batch_op.add_column(sa.Column('desc', mysql.VARCHAR(length=128), nullable=True))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_index(batch_op.f('desc'), ['desc'], unique=True)
        batch_op.drop_column('description')

    # ### end Alembic commands ###
