"""empty message

Revision ID: d2f33f3fa954
Revises: 1c468efcf991
Create Date: 2026-03-28 15:02:11.399197

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd2f33f3fa954'
down_revision = '1c468efcf991'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t_user', schema=None) as batch_op:
        batch_op.alter_column('phone',
               existing_type=mysql.VARCHAR(length=11),
               type_=sa.String(length=64),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t_user', schema=None) as batch_op:
        batch_op.alter_column('phone',
               existing_type=sa.String(length=64),
               type_=mysql.VARCHAR(length=11),
               existing_nullable=False)

    # ### end Alembic commands ###
