"""empty message

Revision ID: da222330c5ce
Revises: 337777a36725
Create Date: 2026-04-20 14:44:48.914225

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da222330c5ce'
down_revision = '337777a36725'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('t_order',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.Column('pay_status', sa.Integer(), nullable=True),
    sa.Column('is_send', sa.Integer(), nullable=True),
    sa.Column('fapiao_title', sa.String(length=255), nullable=True),
    sa.Column('fapiao_content', sa.String(length=255), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('uid', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['uid'], ['t_user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('t_express',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('oid', sa.Integer(), nullable=True),
    sa.Column('content', sa.String(length=256), nullable=True),
    sa.Column('update_time', sa.String(length=256), nullable=True),
    sa.ForeignKeyConstraint(['oid'], ['t_order.id'], ),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('t_order_detail',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('oid', sa.Integer(), nullable=True),
    sa.Column('pid', sa.Integer(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.Column('total_price', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['oid'], ['t_order.id'], ),
    sa.ForeignKeyConstraint(['pid'], ['t_product.id'], ),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('t_order_detail')
    op.drop_table('t_express')
    op.drop_table('t_order')
    # ### end Alembic commands ###
