"""empty message

Revision ID: e4e80c1ed7d1
Revises: fc6f9c6a3e68
Create Date: 2026-04-10 22:13:24.294525

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e4e80c1ed7d1'
down_revision = 'fc6f9c6a3e68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t_attribute', schema=None) as batch_op:
        batch_op.alter_column('val',
               existing_type=mysql.VARCHAR(length=64),
               type_=sa.String(length=128),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t_attribute', schema=None) as batch_op:
        batch_op.alter_column('val',
               existing_type=sa.String(length=128),
               type_=mysql.VARCHAR(length=64),
               existing_nullable=True)

    # ### end Alembic commands ###
