"""empty message

Revision ID: f013be3ee6be
Revises: 9c4bd4c3b074
Create Date: 2026-03-19 21:33:55.353775

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f013be3ee6be'
down_revision = '9c4bd4c3b074'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t_menu', schema=None) as batch_op:
        batch_op.alter_column('path',
               existing_type=mysql.VARCHAR(length=64),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t_menu', schema=None) as batch_op:
        batch_op.alter_column('path',
               existing_type=mysql.VARCHAR(length=64),
               nullable=False)

    # ### end Alembic commands ###
