"""empty message

Revision ID: fc6f9c6a3e68
Revises: 05d88e9bede4
Create Date: 2026-04-10 21:56:59.205907

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fc6f9c6a3e68'
down_revision = '05d88e9bede4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t_attribute', schema=None) as batch_op:
        batch_op.alter_column('_type',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.Enum('static', 'dynamic'),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t_attribute', schema=None) as batch_op:
        batch_op.alter_column('_type',
               existing_type=sa.Enum('static', 'dynamic'),
               type_=mysql.INTEGER(display_width=11),
               existing_nullable=True)

    # ### end Alembic commands ###
